# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties (Minecraft 1.20.1)
minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.16.10
loom_version=1.6-SNAPSHOT

# Mod Properties
mod_version=1.0.0
maven_group=com.clussmanproductions.trafficcontrol
archives_base_name=trafficcontrol

# Dependencies
fabric_version=0.92.9+1.20.1
